name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Build
      run: dotnet build -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: CSharpPoet.nupkg.zip
        path: CSharpPoet/bin/Release/*.{nupkg,snupkg}
    - name: Push NuGet package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        dotnet nuget push CSharpPoet/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }}
